modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="arpg_entities"
version="1.0.0"
displayName="ARPG Entities"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="user, MCreator"

[[dependencies.arpg_entities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




